version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-9900}:9900"
    environment:
      NODE_ENV: production
      PORT: 9900
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
